import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Caprasimo } from "next/font/google";

// Font Family Caprasimo declared globally and rendered for all components
// Can be more dynamic to accommodate other fonts: tailwind.config.ts
const caprasimo = Caprasimo({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={caprasimo.className}>{children}</body>
    </html>
  );
}
